--AVERAGING THEE POWER  OUTPUT FROM DIFFERENT YEARS TO HAVE A FAIR AND EASIER COMPARISON BETWEEN COUNTRIES

SELECT COUNTRY, 
(TOTAL_POWER_OUT_GWH_2013 + 
 TOTAL_POWER_OUT_GWH_2014 + 
 TOTAL_POWER_OUT_GWH_2015 + 
 TOTAL_POWER_OUT_GWH_2016 + 
 TOTAL_POWER_OUT_GWH_2017 )/5 AS AVG_OUTPUT_GWH_13_TO_17
FROM TOTAL_POWER_BY_COUNTRY
ORDER BY AVG_OUTPUT_GWH_13_TO_17 DESC;
