--WE FIND OUT WHICH FUELS PRODUCE THE MOST ENERGY OUTPUT
--WEE CREATE A TABLE FOR FURTHER ANALYSIS

CREATE TABLE TOTAL_POWER_BY_FUEL AS (SELECT FUEL_1 AS FUEL,
	SUM(POWER_OUT_2013) AS TOTAL_OUTPUT_2013_GWH,
	SUM(POWER_OUT_2014) AS TOTAL_OUTPUT_2014_GWH,
	SUM(POWER_OUT_2015) AS TOTAL_OUTPUT_2015_GWH,
	SUM(POWER_OUT_2016) AS TOTAL_OUTPUT_2016_GWH,
	SUM(POWER_OUT_2017) AS TOTAL_OUTPUT_2017_GWH
FROM FUEL_TYPES
INNER JOIN POWER_GENERATED_GOLD ON FUEL_TYPES.ID = POWER_GENERATED_GOLD.ID
GROUP BY FUEL)