CREATE VIEW ESTABLISHED_YEAR_BY_FUEL_COUNT AS 
(SELECT COMMISSIONING_YEAR, 
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Coal' THEN ESTABLISHED_YEAR.ID END) AS COAL,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Cogeneration' THEN ESTABLISHED_YEAR.ID END) AS COGENERATION,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Wind' THEN ESTABLISHED_YEAR.ID END) AS WIND,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Solar' THEN ESTABLISHED_YEAR.ID END) AS SOLAR,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Storage' THEN ESTABLISHED_YEAR.ID END) AS STORAGE,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Biomass' THEN ESTABLISHED_YEAR.ID END) AS BIOMASS,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Hydro' THEN ESTABLISHED_YEAR.ID END) AS HYDRO,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Other' THEN ESTABLISHED_YEAR.ID END) AS OTHER,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Gas' THEN ESTABLISHED_YEAR.ID END) AS GAS,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Waste' THEN ESTABLISHED_YEAR.ID END) AS WASTE,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Geothermal' THEN ESTABLISHED_YEAR.ID END) AS GEOTHERMAL,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Petcoke' THEN ESTABLISHED_YEAR.ID END) AS PETCOKE,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Oil' THEN ESTABLISHED_YEAR.ID END) AS OIL,
    COUNT(DISTINCT CASE WHEN FUEL_TYPES.FUEL_1 = 'Nuclear' THEN ESTABLISHED_YEAR.ID END) AS NUCLEAR,
    COUNT(DISTINCT ESTABLISHED_YEAR.ID) AS TOTAL_ESTABLISHED
FROM ESTABLISHED_YEAR
INNER JOIN FUEL_TYPES ON FUEL_TYPES.ID = ESTABLISHED_YEAR.ID
GROUP BY COMMISSIONING_YEAR
ORDER BY COMMISSIONING_YEAR ASC);

SELECT *
FROM ESTABLISHED_YEAR_BY_FUEL_COUNT