CREATE TABLE TOTAL_POWER_BY_COUNTRY AS
	(SELECT COUNTRY_LONG AS COUNTRY,
			SUM(POWER_OUT_2013) AS TOTAL_POWER_OUT_GWH_2013,
			SUM(POWER_OUT_2014) AS TOTAL_POWER_OUT_GWH_2014,
			SUM(POWER_OUT_2015) AS TOTAL_POWER_OUT_GWH_2015,
			SUM(POWER_OUT_2016) AS TOTAL_POWER_OUT_GWH_2016,
			SUM(POWER_OUT_2017) AS TOTAL_POWER_OUT_GWH_2017
		FROM NAME_LOCATION
		INNER JOIN POWER_GENERATED_GOLD ON NAME_LOCATION.ID = POWER_GENERATED_GOLD.ID
		GROUP BY COUNTRY_LONG);
		
		
DELETE FROM TOTAL_POWER_BY_COUNTRY
WHERE TOTAL_POWER_OUT_GWH_2013 IS NULL
      OR TOTAL_POWER_OUT_GWH_2014 IS NULL
      OR TOTAL_POWER_OUT_GWH_2015 IS NULL
      OR TOTAL_POWER_OUT_GWH_2016 IS NULL
      OR TOTAL_POWER_OUT_GWH_2017 IS NULL;
	  
	  
--DELETED ROWS=19