ALTER TABLE FUEL_TYPES RENAME COLUMN GPPD_IDNR TO ID;


ALTER TABLE FUEL_TYPES RENAME COLUMN PRIMARY_FUEL TO FUEL_1;


ALTER TABLE FUEL_TYPES RENAME COLUMN OTHER_FUEL1 TO FUEL_2;


ALTER TABLE FUEL_TYPES RENAME COLUMN OTHER_FUEL2 TO FUEL_3;


ALTER TABLE FUEL_TYPES RENAME COLUMN OTHER_FUEL3 TO FUEL_4;