UPDATE ESTABLISHED_YEAR
SET COMMISSIONING_YEAR = regexp_replace(COMMISSIONING_YEAR, E'\\..*$', '', 'g')
WHERE COMMISSIONING_YEAR ~ E'^\\d+\\.\\d+$';

ALTER TABLE ESTABLISHED_YEAR
RENAME GDDP_IDNR TO ID;
